### ISSUE TITLE
4 vs 6 digit locator in wsprnet db

### ISSUE THREAD

**Issue by helioshk** [HB9VQQ/WSPRBeacon#3]
Hello, congrats for the successful launch of the project!

I noticed that IU2PJI spots are only stored with 4-digit locator in the wsprnet db. 
As far as I know, the 6-digit locator can be supplied by creating an account on wsprnet for the callsign.
Perhaps you, or the operator of the beacon could create an account.

73

**Comment by helioshk** [comment]
I know about the type-2 transmission. But the 6-digit locator is also stored in the database, if the locator is supplied by the transmitters wsprnet profile.

**Comment by HB9VQQ** [comment]
As explained this is not possible

**Comment by helioshk** [comment]
As explained, it is. 
I can do it as well, if you don't want to.

Wsprnet-profiles are also useful otherwise, to give other users information about their setup.
